### ISSUE TITLE
Doesn't work on fresh clone

### ISSUE THREAD

**Issue by ericfrederich** [bneijt/poetry-lock-docker#2]
Please ignore if it is my understanding which is wrong.

On a fresh clone running `./build.sh` gives an error because it cannot find `poetry-lock-package`.

Is `poetry-lock-package` assumed to be installed on the host (like `poetry` is assumed to be installed)?
... or should you run a `poetry install` in  `build.sh` and `build-split.sh` which would install `poetry-lock-package` as a dev dependency?

I added a `poetry install` to `build.sh` and it works... again, just not sure whether that is the correct fix or if I should install `poetry-lock-package` system-wide.

**Comment by bneijt** [comment]
You are right, a `poetry install` is missing to do it from a fresh build.

You are free to install poetry-lock-package as a separate binary and run it from outside of poetry. It reads the `pyproject.toml` and `poetry.lock` from the current directory to figure out the dependencies.

If you have multiple developers working on a project, it's nice to add it as a `--dev` dependency using `poetry add --dev poetry-lock-package`, because then a `poetry install` will just bring it into scope and `poetry run poetry-lock-package` will execute the command.

I'm still working on transitioning this functionality into a poetry plugin ( https://github.com/bneijt/poetry-lock-package/issues/3 ) which should simplify the installation and use.
